vowel.train <- read.csv("https://web.stanford.edu/~hastie/ElemStatLearn/datasets/vowel.train")
vowel.test <- read.csv("https://web.stanford.edu/~hastie/ElemStatLearn/datasets/vowel.test")
vowel.train$y <- factor(vowel.train$y)
vowel.test$y <- factor(vowel.test$y)
set.seed(33833)
library(caret)
rf <- train(y~., data=vowel.train, method="rf")
gbm <- train(y~., data=vowel.train, method="gbm")
mean(predict(rf, vowel.test)==vowel.test$y)
mean(predict(gbm, vowel.test)==vowel.test$y)
mean(predict(rf, vowel.test)==predict(gbm, vowel.test))